frr defaults traditional
hostname R3
no ipv6 forwarding
!
interface lo
 ip address 3.3.3.3/32
exit
!
interface eth1
 ip address 192.168.13.3/24
exit
!
interface eth2
 ip address 192.168.34.3/24
exit
!
interface eth3
 ip address 192.168.35.3/24
exit
!
interface eth4
 ip address 192.168.36.3/24
exit
!
router ospf
 network 192.168.13.0/24 area 0
 network 192.168.34.0/24 area 0
 network 192.168.35.0/24 area 0
 network 192.168.36.0/24 area 0
 network 3.3.3.3/32 area 0
exit
!
