frr defaults traditional
hostname R4
no ipv6 forwarding
!
interface lo
 ip address 4.4.4.4/32
exit
!
interface eth1
 ip address 192.168.24.4/24
exit
!
interface eth2
 ip address 192.168.34.4/24
exit
!
interface eth3
 ip address 192.168.46.4/24
exit
!
interface eth4
 ip address 192.168.45.4/24
exit
!
router ospf
 network 192.168.24.0/24 area 0
 network 192.168.34.0/24 area 0
 network 192.168.45.0/24 area 0
 network 192.168.46.0/24 area 0
 network 4.4.4.4/32 area 0
exit
!
