service integrated-vtysh-config
frr defaults traditional
hostname CE21
no ipv6 forwarding
!
interface eth1
 ip address 10.0.121.2/30
exit
!
interface eth2
 ip address 172.4.0.1/24
exit
!
interface lo
 ip address 21.21.21.21/32
exit
!
router bgp 21
 no bgp ebgp-requires-policy
 neighbor 10.0.121.1 remote-as 200
 network 172.4.0.0/24
exit
!







