service integrated-vtysh-config
frr defaults traditional
hostname CE22
no ipv6 forwarding
!
interface eth1
 ip address 10.0.122.2/30
exit
!
interface eth2
 ip address 172.4.1.1/24
exit
!
interface lo
 ip address 22.22.22.22/32
exit
!
router bgp 22
 no bgp ebgp-requires-policy
 neighbor 10.0.122.1 remote-as 200
 network 172.4.1.0/24
exit
!







