service integrated-vtysh-config
frr defaults traditional
hostname CE33
no ipv6 forwarding
!
interface eth1
 ip address 10.0.133.2/30
exit
!
interface eth2
 ip address 172.4.2.1/24
exit
!
interface lo
 ip address 33.33.33.33/32
exit
!
router bgp 33
 no bgp ebgp-requires-policy
 neighbor 10.0.133.1 remote-as 200
 network 172.4.2.0/24
exit
!







