service integrated-vtysh-config
frr defaults traditional
hostname R1
no ipv6 forwarding
!
interface eth1
 ip address 20.0.14.1/30
exit
!
interface eth2
 ip address 10.0.111.1/30
exit
!
interface eth3
 ip address 20.0.15.1/30
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
router bgp 100
 no bgp ebgp-requires-policy
 neighbor 10.0.111.2 remote-as 11
exit
!






