service integrated-vtysh-config
frr defaults traditional
hostname R2
no ipv6 forwarding
!
interface eth1
 ip address 20.0.24.1/30
exit
!
interface eth2
 ip address 20.0.23.1/30
exit
!
interface eth3
 ip address 10.0.121.1/30
exit
!
interface eth4
 ip address 10.0.122.1/30
exit
!
interface lo
 ip address 2.2.2.2/32
exit
!
router ospf
 network 20.0.24.0/30 area 0
 network 20.0.23.0/30 area 0
 network 2.2.2.2/32 area 0
exit
!
router bgp 200
 no bgp ebgp-requires-policy
 neighbor 10.0.121.2 remote-as 21
 neighbor 10.0.122.2 remote-as 22
 neighbor 4.4.4.4 remote-as 200
 neighbor 4.4.4.4 update-source lo
 neighbor 4.4.4.4 next-hop-self
 neighbor 5.5.5.5 remote-as 200
 neighbor 5.5.5.5 update-source lo
 neighbor 5.5.5.5 next-hop-self
 neighbor 3.3.3.3 remote-as 200
 neighbor 3.3.3.3 update-source lo
 neighbor 3.3.3.3 next-hop-self
exit
!







