service integrated-vtysh-config
frr defaults traditional
hostname R5

no ipv6 forwarding
!
interface eth1
 ip address 20.0.15.2/30
exit
!
interface eth2
 ip address 20.0.35.2/30
exit
!
interface lo
 ip address 5.5.5.5/32
exit
!
router ospf
 network 20.0.35.0/30 area 0
 network 5.5.5.5/32 area 0
exit
!
router bgp 200
 no bgp ebgp-requires-policy
 neighbor 3.3.3.3 remote-as 200
 neighbor 3.3.3.3 update-source lo
 neighbor 3.3.3.3 next-hop-self
 neighbor 4.4.4.4 remote-as 200
 neighbor 4.4.4.4 update-source lo
 neighbor 4.4.4.4 next-hop-self
 neighbor 2.2.2.2 remote-as 200
 neighbor 2.2.2.2 update-source lo
 neighbor 2.2.2.2 next-hop-self
exit
!






