service integrated-vtysh-config
frr defaults traditional
hostname R3
no ipv6 forwarding
!
interface eth1
 ip address 10.0.13.2/30
exit
!
interface eth2
 ip address 10.0.34.1/30
exit
!
interface lo
 ip address 3.3.3.3/32
exit
!
end





