service integrated-vtysh-config
frr defaults traditional
hostname R1
no ipv6 forwarding
!
interface eth1
 ip address 10.0.123.1/24
exit
!
interface eth2
 ip address 192.168.1.1/24
exit
!
interface lo
 ip address 10.0.1.1/32
exit
!
interface lo1
 ip address 20.0.1.1/24
exit
!
interface lo2
 ip address 20.0.2.1/24
exit
!
interface lo3
 ip address 20.0.3.1/24
exit
!
interface lo4
 ip address 20.0.4.1/24
exit
!







