service integrated-vtysh-config
frr defaults traditional
hostname R2
no ipv6 forwarding
!
interface eth1
 ip address 10.0.123.2/24
exit
!
interface eth2
 ip address 10.0.24.2/24
exit
!
interface eth3
 ip address 10.0.26.2/24
exit
!
interface lo
 ip address 10.0.2.1/32
exit
!
