service integrated-vtysh-config
frr defaults traditional
hostname R4
no ipv6 forwarding
!
interface eth1
 ip address 10.0.24.4/24
exit
!
interface eth2
 ip address 10.0.46.4/24
exit
!
interface eth3
 ip address 10.0.45.4/24
exit
!
interface lo
 ip address 10.0.4.1/32
exit
!
