service integrated-vtysh-config
frr defaults traditional
hostname R5
no ipv6 forwarding
!
interface eth1
 ip address 10.0.45.5/24
exit
!
interface eth2
 ip address 10.0.56.5/24
exit
!
interface eth3
 ip address 192.168.2.1/24
exit
!
interface lo
 ip address 10.0.5.1/32
exit
!
