service integrated-vtysh-config
frr defaults traditional
hostname R1
no ipv6 forwarding
!
interface eth1
 ip address 20.0.13.1/30
 ip ospf network point-to-point
 ip ospf hello-interval 2
 ip ospf dead-interval 10
 link-params
  enable
 exit-link-params
exit
!
interface eth2
 ip address 20.0.12.1/30
 ip ospf network point-to-point
 ip ospf hello-interval 2
 ip ospf dead-interval 10
 link-params
  enable
 exit-link-params
exit
!
interface eth3
 ip address 192.168.111.1/24
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0.0.0.0
 network 20.0.0.0/16 area 0.0.0.0
 capability opaque
 mpls-te on
 mpls-te router-address 1.1.1.1
 router-info area 0.0.0.0
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing node-msd 8
 segment-routing prefix 1.1.1.1/32 index 100
exit
!
router bgp 100
 bgp router-id 1.1.1.1
 neighbor 5.5.5.5 remote-as 100
 neighbor 5.5.5.5 update-source lo
 !
 address-family ipv4 unicast
  network 192.168.111.0/24
 exit-address-family
exit
!
line vty
!
