service integrated-vtysh-config
frr defaults traditional
hostname R1
no ipv6 forwarding
!
interface eth1
 ip address 192.168.110.65/26
exit
!
interface eth4
 ip address 192.168.110.193/26
exit
!
interface eth2
 ip address 10.0.12.1/30
exit
!
interface eth3
 ip address 10.0.13.1/30
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
end